/*
 * Code for class WEL_CB_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F979_8899(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8900(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8901(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8902(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8903(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8904(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8905(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8906(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8907(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8908(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8909(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8910(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8911(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8912(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8913(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8914(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8915(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8916(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8917(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8918(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8919(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8920(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8921(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8922(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8923(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8924(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8925(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8926(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8927(EIF_REFERENCE);
extern EIF_TYPED_VALUE F979_8928(EIF_REFERENCE);
extern void EIF_Minit979(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {WEL_CB_CONSTANTS}.cb_geteditsel */
EIF_TYPED_VALUE F979_8899 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 320L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_limittext */
EIF_TYPED_VALUE F979_8900 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 321L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_seteditsel */
EIF_TYPED_VALUE F979_8901 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 322L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_addstring */
EIF_TYPED_VALUE F979_8902 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 323L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_deletestring */
EIF_TYPED_VALUE F979_8903 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 324L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_dir */
EIF_TYPED_VALUE F979_8904 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 325L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_getcount */
EIF_TYPED_VALUE F979_8905 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 326L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_getcursel */
EIF_TYPED_VALUE F979_8906 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 327L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_getlbtext */
EIF_TYPED_VALUE F979_8907 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 328L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_getlbtextlen */
EIF_TYPED_VALUE F979_8908 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 329L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_insertstring */
EIF_TYPED_VALUE F979_8909 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 330L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_resetcontent */
EIF_TYPED_VALUE F979_8910 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 331L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_findstring */
EIF_TYPED_VALUE F979_8911 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 332L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_selectstring */
EIF_TYPED_VALUE F979_8912 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 333L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_setcursel */
EIF_TYPED_VALUE F979_8913 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 334L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_showdropdown */
EIF_TYPED_VALUE F979_8914 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 335L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_getitemdata */
EIF_TYPED_VALUE F979_8915 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 336L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_setitemdata */
EIF_TYPED_VALUE F979_8916 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 337L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_getdroppedcontrolrect */
EIF_TYPED_VALUE F979_8917 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 338L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_setitemheight */
EIF_TYPED_VALUE F979_8918 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 339L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_getitemheight */
EIF_TYPED_VALUE F979_8919 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 340L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_setextendedui */
EIF_TYPED_VALUE F979_8920 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 341L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_getextendedui */
EIF_TYPED_VALUE F979_8921 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 342L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_getdroppedstate */
EIF_TYPED_VALUE F979_8922 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 343L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_findstringexact */
EIF_TYPED_VALUE F979_8923 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 344L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_okay */
EIF_TYPED_VALUE F979_8924 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_err */
EIF_TYPED_VALUE F979_8925 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -1L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_errspace */
EIF_TYPED_VALUE F979_8926 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -2L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_gettopindex */
EIF_TYPED_VALUE F979_8927 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 347L);
	return r;
}

/* {WEL_CB_CONSTANTS}.cb_settopindex */
EIF_TYPED_VALUE F979_8928 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 348L);
	return r;
}

void EIF_Minit979 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
